app-template:
  defaultPodOptions:
    enableServiceLinks: true
    securityContext:
      runAsUser: 1029
      runAsGroup: 100
      fsGroup: 100
  controllers:
    main:
      containers:
        lidarr:
          image: { repository: docker.io/linuxserver/lidarr, tag: 3.0.1 }
          securityContext:
            runAsUser: 0
          env:
            PUID: 1029
            PGID: 100
            UMASK: 002
  service:
    main:
      controller: main
      ports:
        lidarr:
          port: 8686
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &lidarrHost lidarr.malford.io
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: lidarr
      tls:
        - secretName: lidarr-tls-certificate
          hosts:
            - *lidarrHost
  persistence:
    media:
      type: persistentVolumeClaim
      existingClaim: jellyfin-media
      globalMounts:
        - path: /media
    config:
      enabled: true
      type: persistentVolumeClaim
      storageClass: standard-rwo
      accessMode: ReadWriteOnce
      size: 20Gi
      advancedMounts:
        main:
          lidarr:
            - path: /config
              subPath: lidarr
    downloads:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: downloads-shared
      advancedMounts:
        main:
          lidarr:
            - path: /downloads
